title: Xinyi Zhao
logo: assets/img/20200929_9745_processed.jpg
show_downloads: false
theme: jekyll-theme-minimal


description: >
  ğŸ“§ <a href="mailto:zhao@mpidr.mpg.de">zhao@mpidr.mpg.de</a><br>
  ğŸ”— <a href="https://www.linkedin.com/in/xinyi-zhao-38b3b61b7">LinkedIn</a><br>
  ğŸ“ <a href="https://scholar.google.com/citations?user=U2JNVEwAAAAJ&hl=en">Google Scholar</a><br>
  ğŸ†” <a href="https://orcid.org/0000-0002-2552-7795">ORCID</a>


