title: Xinyi Zhao
logo: assets/img/20200929_9745_processed.jpg
show_downloads: false
theme: jekyll-theme-minimal 

description: >
  ğŸ“§ zhao@mpidr.mpg.de 
  ğŸ”— [LinkedIn](www.linkedin.com/in/xinyi-zhao-38b3b61b7)  
  ğŸ“ [Google Scholar](https://scholar.google.com/citations?user=U2JNVEwAAAAJ&hl=en)
  ğŸ†” [ORCID](https://orcid.org/0000-0002-2552-7795)
